[FIX] hr: prevent error on removing dismissal date
Currently, an error occurs when user removes dismissal date on
`End of Collaboration` form.

Steps to replicate:
- Install `hr` with demo.
- Open any employee > Click on cog button > End of Collaboration.
- Remove value from `Dismissal date` and click else where.

Error:
```
  File "/home/odoo/odoo19/community/addons/hr/models/hr_employee_departure.py", line 56, in _compute_action_date
    if departure.action_date and departure.action_date < departure.departure_date:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'datetime.date' and 'bool'
```

Cause:
- As dismissal date is assigned from departure date [here] and the user removed
  the value from dismissal date so we receive it as false.
- So, we receive the error from [this] line, as `departure.departure_date` is
  received as False.

Solution:
- Added a conditional check for `departure_date` before the date comparison.

[here]: https://github.com/odoo/odoo/blob/a9d1b7ad18cfbc90fa415af6675518d687f072f9/addons/hr/models/hr_employee_departure.py#L51

[this]: https://github.com/odoo/odoo/blob/a9d1b7ad18cfbc90fa415af6675518d687f072f9/addons/hr/models/hr_employee_departure.py#L56

No ID

closes odoo/odoo#261085

X-original-commit: 59c072901aa3006166924896699961a738a1e280
Signed-off-by: Mélanie Peyrat (mepe) <mepe@odoo.com>
Signed-off-by: Bhavya Ashesh Nanavati (bhna) <bhna@odoo.com>