[FIX] l10n_pl_edi: avoid AttributeError when KSeF rate limit is reached
Before this commit:
Steps

1. Create a Polish company
2. Run scheduled action "Polish eInvoice: Download vendor bills from KSeF"
3. If the customer gets 429 Rate Limit
=> A traceback error is raised as message isn't an atrribute in KSeFRateLimitError object
`AttributeError: 'KSeFRateLimitError' object has no attribute 'message'`

This happens because `KSeFRateLimitError` does not define a `message`
attribute. The message is only passed to the base Exception and stored
in `args`.

After this commit:
Use `str(e)` to properly retrieve the exception message and avoid the
AttributeError.

opw-6009380

closes odoo/odoo#254562

X-original-commit: 073d8e6714b123a37cf9fe5e3755bda7bb97638f
Signed-off-by: Hugo Poncelet (hupo) <hupo@odoo.com>
Signed-off-by: Ahmed Abdelaziz Hasaneen (aaha) <aaha@odoo.com>